name    'jdowning/awscli'
version '1.0.0'
source 'https://github.com/justindowning/puppet-awscli'
author 'Justin Downing'
license 'Apache License, Version 2.0'
summary 'Install awscli'
description 'Install awscli'
project_page 'https://github.com/justindowning/puppet-awscli'
dependency 'stahnma/epel', '>=0.1.0'
