name    'jdowning/awscli'
version '0.2.0'
source 'https://github.com/justindowning/puppet-awscli'
author 'Justin Downing'
license 'Apache License, Version 2.0'
summary 'Install awscli'
description 'Install awscli'
project_page 'https://github.com/justindowning/puppet-awscli'
